/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TgAmbulanceWlList {
    }
}
declare global {
    interface HTMLTgAmbulanceWlListElement extends Components.TgAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLTgAmbulanceWlListElement: {
        prototype: HTMLTgAmbulanceWlListElement;
        new (): HTMLTgAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "tg-ambulance-wl-list": HTMLTgAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface TgAmbulanceWlList {
    }
    interface IntrinsicElements {
        "tg-ambulance-wl-list": TgAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tg-ambulance-wl-list": LocalJSX.TgAmbulanceWlList & JSXBase.HTMLAttributes<HTMLTgAmbulanceWlListElement>;
        }
    }
}
